# Generated by Django 3.1 on 2020-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seeds', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('blackout', models.IntegerField()),
                ('harvest', models.IntegerField()),
                ('output', models.IntegerField()),
            ],
        ),
    ]
