# Generated by Django 3.1 on 2020-11-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('medium_weight', models.IntegerField()),
                ('seeds_weight', models.IntegerField()),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.medium')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.plant')),
            ],
        ),
    ]
