# Generated by Django 3.1 on 2020-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_tray_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tray',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
