# Generated by Django 3.1 on 2020-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
