# Generated by Django 3.1 on 2020-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_plant_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='fname',
        ),
        migrations.AddField(
            model_name='tray',
            name='fname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
