# Generated by Django 3.1 on 2020-12-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerOharvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('output', models.IntegerField(blank=True, null=True)),
                ('tray_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Old',
        ),
    ]
