# Generated by Django 3.1 on 2020-12-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20201206_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmerOharvest',
            new_name='Oharvest',
        ),
    ]
