# Generated by Django 3.1 on 2020-12-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_farmerold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmerOld',
            new_name='Old',
        ),
    ]
