# Generated by Django 3.1 on 2020-12-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_auto_20201206_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oharvest',
        ),
        migrations.DeleteModel(
            name='Old',
        ),
    ]
