# Generated by Django 3.1 on 2020-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_auto_20201206_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='location',
            field=models.CharField(default='Hamze', max_length=255),
            preserve_default=False,
        ),
    ]
