# Generated by Django 2.2.16 on 2024-06-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0017_auto_20240610_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='packweight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BulkHarvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trays', models.IntegerField()),
                ('Harvestdate', models.DateField()),
                ('PacksQtt', models.IntegerField()),
                ('PacksWeight', models.IntegerField()),
                ('MixWeight', models.IntegerField()),
                ('MediumWeightpacks', models.IntegerField()),
                ('MediumWeightMix', models.IntegerField()),
                ('SeedsWeightPacks', models.IntegerField()),
                ('SeedsWeightMix', models.IntegerField()),
                ('MediumMix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmer.Medium')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmer.Plant')),
            ],
        ),
    ]
