# Generated by Django 2.2.16 on 2024-06-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0018_auto_20240610_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='output',
            new_name='medium_weight',
        ),
    ]
