# Generated by Django 2.2.16 on 2024-07-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0019_auto_20240610_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
