# Generated by Django 2.2.16 on 2024-09-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0020_auto_20240721_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='bulkh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.BulkHarvest'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tray',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmer.Medium'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmer.Plant'),
        ),
    ]
