# Generated by Django 4.2.19 on 2025-09-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0021_auto_20240906_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
