# Generated by Django 4.2.19 on 2025-09-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0023_alter_bulkharvest_id_alter_harvest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
